//auto generated by go-cli

package config

import (
	_ "embed"

	"github.com/candbright/go-core/config"
)

//go:embed server.yaml
var serverConfigData []byte

var ServerConfig *config.Config

func init() {
	cfg, err := config.Parse(serverConfigData, config.YAML)
	if err != nil {
		panic(err)
	}
	ServerConfig = cfg
}
